-- 1)Conoscere per ciascuna competenza il numero di tecnici a disposizione

SELECT C.ID, COUNT(T.ID_TECNICO) AS NUMEROTECNICI
FROM COMPETENZA C LEFT JOIN TECNICO_COMPETENZA T
ON C.ID=T.ID_COMPETENZA
GROUP BY C.ID;

-- 2)Conoscere il numero clienti per ciascuna zona disservita (permette di conoscere anche il numero di clienti per antenna)

CREATE TEMPORARY TABLE NCLIENTI_ANTENNE AS
SELECT DISTINCT COUNT(*) AS NCLIENTI, PC.ANTENNA_ID AS ANTENNA FROM MODEM M
JOIN PERCORSOCLIENTE PC ON M.ID = PC.MODEM_ID
WHERE (M.CAVO_ID IS NULL AND PC.CAVO_ID IS NULL)
GROUP BY PC.ANTENNA_ID;

SELECT A.REGIONE, A.PROVINCIA, A.COMUNE, NCA.NCLIENTI, A.ID AS 'ANTENNA' FROM ANTENNA A
JOIN NCLIENTI_ANTENNE NCA ON NCA.ANTENNA = A.ID; 

-- 3)Conoscere per ciascun contratto il relativo costo di attivazione e il costo mensile

CREATE TEMPORARY TABLE COSTODATI AS
SELECT D.COSTODIATTIVAZIONE AS CA_DATI, D.COSTOMENSILE AS CM_DATI,  CONTRATTO_ID AS CONTRATTO FROM CONTRATTO_DATI CD
JOIN DATI D ON D.ID = CD.DATI_ID
ORDER BY CD.CONTRATTO_ID ASC;

CREATE TEMPORARY TABLE COSTOFONIA AS
SELECT F.COSTOATTIVAZIONE AS CA_FONIA, F.COSTOMENSILE AS CM_FONIA, CONTRATTO_ID AS CONTRATTO FROM CONTRATTO_FONIA CF
JOIN FONIA F ON F.ID = CF.FONIA_ID
ORDER BY CF.CONTRATTO_ID ASC;

SELECT  CD.CONTRATTO, ROUND(SUM(CF.CA_FONIA+CD.CA_DATI), 2) AS 'COSTOATTIVAZIONEPACCHETTO', ROUND(SUM(CD.CM_DATI + CF.CM_FONIA), 2) AS 'COSTOMENSILEPACCHETTO', C.COSTORESCISSIONE FROM COSTOFONIA CF
JOIN COSTODATI CD ON CD.CONTRATTO = CF.CONTRATTO
JOIN CONTRATTO C ON C.ID = CF.CONTRATTO
GROUP BY CD.CONTRATTO;


-- 4) Mostrare ID, Nome, Cognome, Area di Competenza e tempo medio di risoluzione dei guasti,
-- tenendo conto che non tutti i guasti hanno importanza uguale; dati i seguenti pesi per ogni livello di guasto: 
-- (0.10 bassa, 0.20 media, 0.30 alta, 0.40 top), fare la media ponderata con il tempo di risoluzione. 
-- Usare la tabella Storico Guasto.

CREATE VIEW TECCOMP AS SELECT ID_TECNICO, GROUP_CONCAT(ID_COMPETENZA) AS AREACOMPETENZA
FROM TECNICO_COMPETENZA
GROUP BY ID_TECNICO;

SELECT T.ID, T.NOME,T.COGNOME, TC.AREACOMPETENZA,
ROUND(SUM(SG.TEMPODIRISOLUZIONE * VG.NUMERO)/COUNT(*),2) AS TEMPOMEDIOPERGUASTO FROM ((STORICOGUASTO SG
RIGHT JOIN TECNICO T ON SG.TECNICOASSEGNATO = T.ID)
JOIN TECCOMP TC ON T.ID = TC.ID_TECNICO)
JOIN VALOREGUASTO VG ON VG.VALORE = SG.PRIORITAGUASTO
GROUP BY T.ID
ORDER BY T.ID;


-- 5)Controllare per ciascuna infrastruttura ( antenna, cavo, ripartilinea) il numero di guasti segnalati su tale linea

SELECT 'CAVO' AS TIPOELEMENTO, PC.CAVO_ID AS IDELEMENTO, COUNT(G.ID) AS NGUASTI FROM PERCORSOCLIENTE PC
JOIN GUASTO G ON PC.ID = G.ID_PERCORSOCLIENTE AND G.ELEMENTOGUASTO = 'CAVO' 
WHERE PC.CAVO_ID IS NOT NULL 
GROUP BY PC.CAVO_ID
UNION ALL
SELECT 'RIPARTILINEA' AS TIPOELEMENTO, PC.RIPARTILINEA_ID AS IDELEMENTO, COUNT(G.ID) AS NGUASTI FROM PERCORSOCLIENTE PC
JOIN GUASTO G ON PC.ID = G.ID_PERCORSOCLIENTE AND G.ELEMENTOGUASTO = 'RIPARTILINEA' 
WHERE PC.RIPARTILINEA_ID IS NOT NULL 
GROUP BY PC.RIPARTILINEA_ID
UNION ALL
SELECT 'CENTRALE' AS TIPOELEMENTO, PC.CENTRALE_ID AS IDELEMENTO, COUNT(G.ID) AS NGUASTI FROM PERCORSOCLIENTE PC
JOIN GUASTO G ON PC.ID = G.ID_PERCORSOCLIENTE AND G.ELEMENTOGUASTO = 'CENTRALE' 
WHERE PC.CENTRALE_ID IS NOT NULL 
GROUP BY PC.CENTRALE_ID
UNION ALL
SELECT 'ANTENNA' AS TIPOELEMENTO, PC.ANTENNA_ID AS IDELEMENTO, COUNT(G.ID) AS NGUASTI FROM PERCORSOCLIENTE PC
JOIN GUASTO G ON PC.ID = G.ID_PERCORSOCLIENTE AND G.ELEMENTOGUASTO = 'ANTENNA' 
WHERE PC.ANTENNA_ID IS NOT NULL 
GROUP BY PC.ANTENNA_ID
UNION ALL
SELECT 'MODEM' AS TIPOELEMENTO, PC.MODEM_ID AS IDELEMENTO, COUNT(G.ID) AS NGUASTI FROM PERCORSOCLIENTE PC
JOIN GUASTO G ON PC.ID = G.ID_PERCORSOCLIENTE AND G.ELEMENTOGUASTO = 'MODEM' 
WHERE PC.MODEM_ID IS NOT NULL 
GROUP BY PC.MODEM_ID
ORDER BY TIPOELEMENTO ASC, IDELEMENTO ASC, NGUASTI ASC;


-- 6)Controllare il numero ed il tipo operazioni che ciascun tecnico ha eseguito

SELECT 
    T.ID AS TECNICO_ID,
    TG.OP_GUASTO AS OP_GUASTO,
    TA.OP_ATTIVAZIONE AS OP_ATTIVAZIONE,
    TR.OP_RITIRO AS OP_RITIRO
FROM TECNICO T
LEFT JOIN
    (SELECT TECNICO_ID, COUNT(GUASTO_ID) AS OP_GUASTO FROM TECNICO_GUASTO GROUP BY TECNICO_ID) TG
ON T.ID = TG.TECNICO_ID
LEFT JOIN 
    (SELECT ID_TECNICO AS TECNICO_ID, COUNT(ID_ATTIVAZIONE) AS OP_ATTIVAZIONE FROM TECNICO_ATTIVAZIONE GROUP BY ID_TECNICO) TA
ON TG.TECNICO_ID = TA.TECNICO_ID
LEFT JOIN 
    (SELECT ID_TECNICO AS TECNICO_ID, COUNT(ID_MODEM) AS OP_RITIRO FROM RITIRO GROUP BY ID_TECNICO) TR
ON TG.TECNICO_ID =TR.TECNICO_ID;



-- 7)Assegnare le nuove attivazioni ai tecnici disponibili

CREATE TEMPORARY TABLE PC AS SELECT PERCORSOCLIENTE_ID, ID
FROM ATTIVAZIONE
WHERE STATO ='DA FARE';

CREATE TEMPORARY TABLE IDC AS SELECT P.CENTRALE_ID, P.ID
FROM PERCORSOCLIENTE P
WHERE (P.ID IN (SELECT PC.PERCORSOCLIENTE_ID FROM PC)) AND P.CENTRALE_ID IS NOT NULL;

CREATE TEMPORARY TABLE IDA AS SELECT P.ANTENNA_ID, P.ID
FROM PERCORSOCLIENTE P
WHERE (P.ID IN (SELECT PC.PERCORSOCLIENTE_ID FROM PC)) AND P.ANTENNA_ID IS NOT NULL;

CREATE TEMPORARY TABLE IDT AS (SELECT C.ID_TERRITORIO, C.ID
FROM CENTRALE C
WHERE C.ID IN (SELECT IDC.CENTRALE_ID FROM IDC))
UNION
(SELECT A.ID_TERRITORIO, A.ID FROM ANTENNA A
WHERE A.ID IN (SELECT IDA.ANTENNA_ID FROM IDA));

CREATE TEMPORARY TABLE TECTER AS SELECT T.ID, T.ID_TERRITORIO
FROM TECNICO T
WHERE (T.ID_TERRITORIO IN (SELECT IDT.ID_TERRITORIO FROM IDT)) AND T.DISPONIBILITA = 'ATTIVO';

INSERT INTO TECNICO_ATTIVAZIONE (ID_ATTIVAZIONE, ID_TECNICO)
(SELECT PC.ID AS IDATTIVAZIONE, TECTER.ID AS IDTECNICO
FROM (((PC JOIN IDC ON PC.PERCORSOCLIENTE_ID = IDC.ID) JOIN IDT ON IDC.CENTRALE_ID = IDT.ID)
JOIN TECTER ON IDT.ID_TERRITORIO = TECTER.ID_TERRITORIO)
LIMIT 1);

INSERT INTO TECNICO_ATTIVAZIONE (ID_ATTIVAZIONE, ID_TECNICO)
(SELECT PC.ID AS IDATTIVAZIONE, TECTER.ID AS IDTECNICO
FROM (((PC JOIN IDA ON PC.PERCORSOCLIENTE_ID = IDA.ID) JOIN IDT ON IDA.ANTENNA_ID = IDT.ID)
JOIN TECTER ON IDT.ID_TERRITORIO = TECTER.ID_TERRITORIO)
LIMIT 1);


-- 8)Assegnare i nuovi guasti ai tecnici disponibili

CREATE TEMPORARY TABLE PC AS SELECT PERCORSOCLIENTE_ID, ID
FROM GUASTO
WHERE STATO ='DA ASSEGNARE';

CREATE TEMPORARY TABLE IDC AS SELECT P.CENTRALE_ID, P.ID
FROM PERCORSOCLIENTE P
WHERE (P.ID IN (SELECT PC.PERCORSOCLIENTE_ID FROM PC)) AND P.CENTRALE_ID IS NOT NULL;

CREATE TEMPORARY TABLE IDA AS SELECT P.ANTENNA_ID, P.ID
FROM PERCORSOCLIENTE P
WHERE (P.ID IN (SELECT PC.PERCORSOCLIENTE_ID FROM PC)) AND P.ANTENNA_ID IS NOT NULL;

CREATE TEMPORARY TABLE IDT AS (SELECT C.ID_TERRITORIO, C.ID
FROM CENTRALE C
WHERE C.ID IN (SELECT IDC.CENTRALE_ID FROM IDC))
UNION
(SELECT A.ID_TERRITORIO, A.ID FROM ANTENNA A
WHERE A.ID IN (SELECT IDA.ANTENNA_ID FROM IDA));

CREATE TEMPORARY TABLE TECTER AS SELECT T.ID, T.ID_TERRITORIO
FROM TECNICO T
WHERE (T.ID_TERRITORIO IN (SELECT IDT.ID_TERRITORIO FROM IDT)) AND T.DISPONIBILITA = 'ATTIVO';

INSERT INTO TECNICO_GUASTO (ID_GUASTO, ID_TECNICO)
(SELECT PC.ID AS IDGUASTO, TECTER.ID AS IDTECNICO
FROM (((PC JOIN IDC ON PC.PERCORSOCLIENTE_ID = IDC.ID) JOIN IDT ON IDC.CENTRALE_ID = IDT.ID)
JOIN TECTER ON IDT.ID_TERRITORIO = TECTER.ID_TERRITORIO)
LIMIT 1);

INSERT INTO TECNICO_GUASTO (ID_GUASTO, ID_TECNICO)
(SELECT PC.ID AS IDGUASTO, TECTER.ID AS IDTECNICO
FROM (((PC JOIN IDA ON PC.PERCORSOCLIENTE_ID = IDA.ID) JOIN IDT ON IDA.ANTENNA_ID = IDT.ID)
JOIN TECTER ON IDT.ID_TERRITORIO = TECTER.ID_TERRITORIO)
LIMIT 1);


-- 9)Assegnare il ritiro dei modem guasti ai tecnici disponibili

INSERT INTO RITIRO (DETTAGLI, DATARITIRO, ID_MODEM, ID_TECNICO)  
SELECT DISTINCT NULL, CURDATE(), M.ID AS MODEMID, T.ID AS TECNICOID
FROM MODEM M
JOIN PERCORSOCLIENTE PC ON PC.MODEM_ID = M.ID
JOIN CENTRALE C ON C.ID = PC.CENTRALE_ID
JOIN TECNICO T ON T.ID_TERRITORIO = C.ID_TERRITORIO
WHERE M.STATO = 'GUASTO' AND T.DISPONIBILITA = 'ATTIVO';


-- 10)Mostrare quali apparati della rete infrastrutturale hanno bisogno di riparazione

CREATE VIEW GRL AS SELECT DISTINCT P.RIPARTILINEA_ID
FROM PERCORSOCLIENTE P JOIN (SELECT * FROM GUASTO G
WHERE G.ELEMENTOGUASTO='RIPARTILINEA' AND G.ID NOT IN (SELECT S.GUASTO_ID FROM STORICOGUASTO S)) RL
ON P.ID=RL.ID_PERCORSOCLIENTE;

CREATE VIEW GCE AS SELECT DISTINCT P.CENTRALE_ID
FROM PERCORSOCLIENTE P JOIN (SELECT * FROM GUASTO G
WHERE G.ELEMENTOGUASTO='CENTRALE' AND G.ID NOT IN (SELECT S.GUASTO_ID FROM STORICOGUASTO S)) CE
ON P.ID=CE.ID_PERCORSOCLIENTE;

CREATE VIEW GCA AS SELECT DISTINCT P.CAVO_ID
FROM PERCORSOCLIENTE P JOIN (SELECT * FROM GUASTO G
WHERE G.ELEMENTOGUASTO='CAVO' AND G.ID NOT IN (SELECT S.GUASTO_ID FROM STORICOGUASTO S)) CA
ON P.ID=CA.ID_PERCORSOCLIENTE;

CREATE VIEW GA AS SELECT DISTINCT P.ANTENNA_ID
FROM PERCORSOCLIENTE P JOIN (SELECT * FROM GUASTO G
WHERE G.ELEMENTOGUASTO='ANTENNA' AND G.ID NOT IN (SELECT S.GUASTO_ID FROM STORICOGUASTO S)) A
ON P.ID=A.ID_PERCORSOCLIENTE;

SELECT ID
FROM MODEM
WHERE STATO='GUASTO';

-- 11)Inserimento nuovo cliente con contratto associato, mostrando quale combinazione di dati e fonia ha scelto




SELECT ID FROM DATI WHERE DATI.PIANO = 'TURBONET';
SELECT ID FROM FONIA WHERE FONIA.PIANO = 'Piano Family';

INSERT INTO CONTRATTO (DATAINIZIO, DATASCADENZA, COSTORESCISSIONE, METODODIPAGAMENTO)
VALUES (NOW(), DATE_ADD(CURDATE(), INTERVAL 30 DAY), 150, 'Bonifico');
SELECT LAST_INSERT_ID();

INSERT INTO CLIENTE (NOME, COGNOME, INDIRIZZO, ID_CONTRATTO, NUMERO, TIPOLOGIA)
VALUES ('Mario', 'Rossi', 'Via Roma, 1', id_contratto, '1234567890', 3);

INSERT INTO CONTRATTO_DATI (CONTRATTO_ID, DATI_ID) VALUES (id_contratto, id_dati);
INSERT INTO CONTRATTO_FONIA (CONTRATTO_ID, FONIA_ID) VALUES (id_contratto, id_fonia);

SELECT id_contratto as IDCONTRATTO, id_dati AS IDDATI, id_fonia AS IDFONIA;

COMMIT;



-- 12)Rilevamento discrepanze tra competenze dei tecnici e competenze necessarie
-- (Assumiamo che l’azienda abbia bisogno di assumere se possiede meno di 15 tecnici per quella singola competenza
-- o se  il ratio guasti/tecnico risulta maggiore di 8.40)
SELECT 
    TC.ID_COMPETENZA,
    COUNT(DISTINCT ID_TECNICO) AS NTECNICI,
    COUNT(DISTINCT GC.ID_GUASTO) AS NGUASTI,
    ROUND( COUNT(DISTINCT ID_GUASTO) / COUNT(DISTINCT ID_TECNICO), 2) AS GUASTI_PER_TECNICO
FROM TECNICO_COMPETENZA TC
JOIN GUASTO_COMPETENZA GC ON TC.ID_COMPETENZA = GC.ID_COMPETENZA
GROUP BY TC.ID_COMPETENZA
HAVING NTECNICI < 15 OR GUASTI_PER_TECNICO > 8.40;

-- 13)Nuova categorizzazione della zona
-- CASO 1: chiusura di una centrale in una zona

SET @territoriocentrale = (SELECT C.ID_TERRITORIO FROM CENTRALE C WHERE C.ID = X);
DELETE FROM CENTRALE WHERE ID=x;
UPDATE TERRITORIO T SET T.STATO = 'DISSERVITO'
WHERE T.ID = @territoriocentrale;

-- CASO 2: apertura di una centrale in una zona disservita
INSERT INTO CENTRALE (ID, NOME, INDIRIZZO, STATO, ID_TERRITORIO) VALUES
(101, ABC, 'VIA ABC, 1', COSTRUZIONE, X);
UPDATE TERRITORIO T SET T.STATO = 'SERVITO'
WHERE T.ID = X;































